
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { AuthProvider } from "@/contexts/authContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/footer";
import { CheckCircle, XCircle } from "lucide-react";
import ToastProvider from "@/components/toastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Himel's Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-100 flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
          <ToastProvider/>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
