import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { AuthProvider } from "@/contexts/authContext";
import ToastProvider from "@/components/toastProvider";
import BanCheck from "@/components/banCheck";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const queryClient = new QueryClient()
export const metadata = {
  title: "Himel's Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-100 flex flex-col min-h-screen`}
      >
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <Header />
            <BanCheck />
            <main className="min-h-screen">{children}</main>
            <ToastProvider />
            <Footer />
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
